#!/bin/bash

set -e # Errors are fatal
set -x # Show commands

date

echo Downloading WebKit
pushd $INDEX_ROOT
if [ -d "WebKit" ]
then
    echo "Found pre-existing folder; skipping re-download."
else
    git clone git://git.webkit.org/WebKit WebKit
fi
popd

date

echo Downloading WebKit blame
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found existing blame folder; skipping re-download."
else
    git init blame
fi
popd

date

echo Updating git
pushd $GIT_ROOT
git pull
popd

echo Generating blame information
python $MOZSEARCH_PATH/blame/transform-repo.py $GIT_ROOT $BLAME_ROOT

date
